spring:
  application:
    name: altasbase-core

  devtools:
    restart:
      enabled: false

  output:
    ansi:
      enabled: ALWAYS

  security:
      user:
        name: actuator
        password: actuator
        roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: always # 'when_authorized' for prod
      probes:
        enabled: true # for kubernetes liveness/readiness
    prometheus:
      enabled: true

rest-client:
  pool:
    maxTotal: 150
    defaultMaxPerRoute: 50
  timeout:
    connectTimeout: 2s
    responseTimeout: 3s
    connectionRequestTimeout: 1s




