spring:
  application:
    name: altasbase-core

  devtools:
    restart:
      enabled: false

  output:
    ansi:
      enabled: ALWAYS

  security:
      user:
        name: actuator
        password: actuator
        roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: always # 'when_authorized' for prod
      probes:
        enabled: true # for kubernetes liveness/readiness
    prometheus:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:secret}
    issuer: altasbase
    expiration: 900000 # 15 minutes in ms
    refresh-expiration: 604800000 # 7 days in ms
    token-prefix: "Bearer "

  rest-client:
    pool:
      max-total: 150
      default-max-per-route: 50
    timeout:
      connect-timeout: 2s
      response-timeout: 3s
      connection-request-timeout: 1s




