spring:
  datasource:
    url: jdbc:postgresql://atlasbase-core-db.cb8ygw20sk5x.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
