spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atlastbasedb
    username: atlasbase_admin
    password: atlasbase_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    context: staging

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
