spring:
  application:
    name: altasbase-core

  devtools:
    restart:
      enabled: false

  output:
    ansi:
      enabled: ALWAYS

  security:
      user:
        name: actuator
        password: actuator
        roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: always # 'when_authorized' for prod
      probes:
        enabled: true # for kubernetes liveness/readiness
    prometheus:
      enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://frontend-stage.com
      - https://frontend-prod.com
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    max-age: 3600
  jwt:
    secret: ${JWT_SECRET:80949c483f94f84d0ada979485203341}
    issuer: atlasbase
    expiration: 900000 # 15 minutes in ms
    refresh-expiration: 604800000 # 7 days in ms
    token-prefix: "Bearer "

  rest-client:
    pool:
      max-total: 150
      default-max-per-route: 50
    timeout:
      connect-timeout: 2s
      response-timeout: 3s
      connection-request-timeout: 1s

google:
  client-id: 1074439335992-aem366g2qbduc9rmsscu6h6bup49osq5.apps.googleusercontent.com




